// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ManipulationOperations.proto

#ifndef PROTOBUF_ManipulationOperations_2eproto__INCLUDED
#define PROTOBUF_ManipulationOperations_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Column.pb.h"
#include "Operation.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ManipulationOperations_2eproto();
void protobuf_AssignDesc_ManipulationOperations_2eproto();
void protobuf_ShutdownFile_ManipulationOperations_2eproto();

class ManipulationOperation;
class SetOperation;
class DeleteOperation;
class GetOperation;

// ===================================================================

class ManipulationOperation : public ::google::protobuf::Message {
 public:
  ManipulationOperation();
  virtual ~ManipulationOperation();

  ManipulationOperation(const ManipulationOperation& from);

  inline ManipulationOperation& operator=(const ManipulationOperation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ManipulationOperation& default_instance();

  void Swap(ManipulationOperation* other);

  // implements Message ----------------------------------------------

  ManipulationOperation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ManipulationOperation& from);
  void MergeFrom(const ManipulationOperation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StoreInfo store_info = 1;
  inline int store_info_size() const;
  inline void clear_store_info();
  static const int kStoreInfoFieldNumber = 1;
  inline const ::StoreInfo& store_info(int index) const;
  inline ::StoreInfo* mutable_store_info(int index);
  inline ::StoreInfo* add_store_info();
  inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
      store_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
      mutable_store_info();

  // repeated .ColumnValue primary_key = 2;
  inline int primary_key_size() const;
  inline void clear_primary_key();
  static const int kPrimaryKeyFieldNumber = 2;
  inline const ::ColumnValue& primary_key(int index) const;
  inline ::ColumnValue* mutable_primary_key(int index);
  inline ::ColumnValue* add_primary_key();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      primary_key() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_primary_key();

  // @@protoc_insertion_point(class_scope:ManipulationOperation)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::StoreInfo > store_info_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > primary_key_;
  friend void  protobuf_AddDesc_ManipulationOperations_2eproto();
  friend void protobuf_AssignDesc_ManipulationOperations_2eproto();
  friend void protobuf_ShutdownFile_ManipulationOperations_2eproto();

  void InitAsDefaultInstance();
  static ManipulationOperation* default_instance_;
};
// -------------------------------------------------------------------

class SetOperation : public ::google::protobuf::Message {
 public:
  SetOperation();
  virtual ~SetOperation();

  SetOperation(const SetOperation& from);

  inline SetOperation& operator=(const SetOperation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetOperation& default_instance();

  void Swap(SetOperation* other);

  // implements Message ----------------------------------------------

  SetOperation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetOperation& from);
  void MergeFrom(const SetOperation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StoreInfo store_info = 1;
  inline int store_info_size() const;
  inline void clear_store_info();
  static const int kStoreInfoFieldNumber = 1;
  inline const ::StoreInfo& store_info(int index) const;
  inline ::StoreInfo* mutable_store_info(int index);
  inline ::StoreInfo* add_store_info();
  inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
      store_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
      mutable_store_info();

  // repeated .ColumnValue primary_key = 2;
  inline int primary_key_size() const;
  inline void clear_primary_key();
  static const int kPrimaryKeyFieldNumber = 2;
  inline const ::ColumnValue& primary_key(int index) const;
  inline ::ColumnValue* mutable_primary_key(int index);
  inline ::ColumnValue* add_primary_key();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      primary_key() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_primary_key();

  // repeated .ColumnValue value = 3;
  inline int value_size() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline const ::ColumnValue& value(int index) const;
  inline ::ColumnValue* mutable_value(int index);
  inline ::ColumnValue* add_value();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      value() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_value();

  // @@protoc_insertion_point(class_scope:SetOperation)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::StoreInfo > store_info_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > primary_key_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > value_;
  friend void  protobuf_AddDesc_ManipulationOperations_2eproto();
  friend void protobuf_AssignDesc_ManipulationOperations_2eproto();
  friend void protobuf_ShutdownFile_ManipulationOperations_2eproto();

  void InitAsDefaultInstance();
  static SetOperation* default_instance_;
};
// -------------------------------------------------------------------

class DeleteOperation : public ::google::protobuf::Message {
 public:
  DeleteOperation();
  virtual ~DeleteOperation();

  DeleteOperation(const DeleteOperation& from);

  inline DeleteOperation& operator=(const DeleteOperation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteOperation& default_instance();

  void Swap(DeleteOperation* other);

  // implements Message ----------------------------------------------

  DeleteOperation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteOperation& from);
  void MergeFrom(const DeleteOperation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StoreInfo store_info = 1;
  inline int store_info_size() const;
  inline void clear_store_info();
  static const int kStoreInfoFieldNumber = 1;
  inline const ::StoreInfo& store_info(int index) const;
  inline ::StoreInfo* mutable_store_info(int index);
  inline ::StoreInfo* add_store_info();
  inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
      store_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
      mutable_store_info();

  // repeated .ColumnValue primary_key = 2;
  inline int primary_key_size() const;
  inline void clear_primary_key();
  static const int kPrimaryKeyFieldNumber = 2;
  inline const ::ColumnValue& primary_key(int index) const;
  inline ::ColumnValue* mutable_primary_key(int index);
  inline ::ColumnValue* add_primary_key();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      primary_key() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_primary_key();

  // @@protoc_insertion_point(class_scope:DeleteOperation)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::StoreInfo > store_info_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > primary_key_;
  friend void  protobuf_AddDesc_ManipulationOperations_2eproto();
  friend void protobuf_AssignDesc_ManipulationOperations_2eproto();
  friend void protobuf_ShutdownFile_ManipulationOperations_2eproto();

  void InitAsDefaultInstance();
  static DeleteOperation* default_instance_;
};
// -------------------------------------------------------------------

class GetOperation : public ::google::protobuf::Message {
 public:
  GetOperation();
  virtual ~GetOperation();

  GetOperation(const GetOperation& from);

  inline GetOperation& operator=(const GetOperation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetOperation& default_instance();

  void Swap(GetOperation* other);

  // implements Message ----------------------------------------------

  GetOperation* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetOperation& from);
  void MergeFrom(const GetOperation& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StoreInfo store_info = 1;
  inline int store_info_size() const;
  inline void clear_store_info();
  static const int kStoreInfoFieldNumber = 1;
  inline const ::StoreInfo& store_info(int index) const;
  inline ::StoreInfo* mutable_store_info(int index);
  inline ::StoreInfo* add_store_info();
  inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
      store_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
      mutable_store_info();

  // repeated .ColumnValue primary_key = 2;
  inline int primary_key_size() const;
  inline void clear_primary_key();
  static const int kPrimaryKeyFieldNumber = 2;
  inline const ::ColumnValue& primary_key(int index) const;
  inline ::ColumnValue* mutable_primary_key(int index);
  inline ::ColumnValue* add_primary_key();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      primary_key() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_primary_key();

  // repeated .ColumnValue value = 3;
  inline int value_size() const;
  inline void clear_value();
  static const int kValueFieldNumber = 3;
  inline const ::ColumnValue& value(int index) const;
  inline ::ColumnValue* mutable_value(int index);
  inline ::ColumnValue* add_value();
  inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
      value() const;
  inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
      mutable_value();

  // @@protoc_insertion_point(class_scope:GetOperation)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::StoreInfo > store_info_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > primary_key_;
  ::google::protobuf::RepeatedPtrField< ::ColumnValue > value_;
  friend void  protobuf_AddDesc_ManipulationOperations_2eproto();
  friend void protobuf_AssignDesc_ManipulationOperations_2eproto();
  friend void protobuf_ShutdownFile_ManipulationOperations_2eproto();

  void InitAsDefaultInstance();
  static GetOperation* default_instance_;
};
// ===================================================================


// ===================================================================

// ManipulationOperation

// repeated .StoreInfo store_info = 1;
inline int ManipulationOperation::store_info_size() const {
  return store_info_.size();
}
inline void ManipulationOperation::clear_store_info() {
  store_info_.Clear();
}
inline const ::StoreInfo& ManipulationOperation::store_info(int index) const {
  // @@protoc_insertion_point(field_get:ManipulationOperation.store_info)
  return store_info_.Get(index);
}
inline ::StoreInfo* ManipulationOperation::mutable_store_info(int index) {
  // @@protoc_insertion_point(field_mutable:ManipulationOperation.store_info)
  return store_info_.Mutable(index);
}
inline ::StoreInfo* ManipulationOperation::add_store_info() {
  // @@protoc_insertion_point(field_add:ManipulationOperation.store_info)
  return store_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
ManipulationOperation::store_info() const {
  // @@protoc_insertion_point(field_list:ManipulationOperation.store_info)
  return store_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
ManipulationOperation::mutable_store_info() {
  // @@protoc_insertion_point(field_mutable_list:ManipulationOperation.store_info)
  return &store_info_;
}

// repeated .ColumnValue primary_key = 2;
inline int ManipulationOperation::primary_key_size() const {
  return primary_key_.size();
}
inline void ManipulationOperation::clear_primary_key() {
  primary_key_.Clear();
}
inline const ::ColumnValue& ManipulationOperation::primary_key(int index) const {
  // @@protoc_insertion_point(field_get:ManipulationOperation.primary_key)
  return primary_key_.Get(index);
}
inline ::ColumnValue* ManipulationOperation::mutable_primary_key(int index) {
  // @@protoc_insertion_point(field_mutable:ManipulationOperation.primary_key)
  return primary_key_.Mutable(index);
}
inline ::ColumnValue* ManipulationOperation::add_primary_key() {
  // @@protoc_insertion_point(field_add:ManipulationOperation.primary_key)
  return primary_key_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
ManipulationOperation::primary_key() const {
  // @@protoc_insertion_point(field_list:ManipulationOperation.primary_key)
  return primary_key_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
ManipulationOperation::mutable_primary_key() {
  // @@protoc_insertion_point(field_mutable_list:ManipulationOperation.primary_key)
  return &primary_key_;
}

// -------------------------------------------------------------------

// SetOperation

// repeated .StoreInfo store_info = 1;
inline int SetOperation::store_info_size() const {
  return store_info_.size();
}
inline void SetOperation::clear_store_info() {
  store_info_.Clear();
}
inline const ::StoreInfo& SetOperation::store_info(int index) const {
  // @@protoc_insertion_point(field_get:SetOperation.store_info)
  return store_info_.Get(index);
}
inline ::StoreInfo* SetOperation::mutable_store_info(int index) {
  // @@protoc_insertion_point(field_mutable:SetOperation.store_info)
  return store_info_.Mutable(index);
}
inline ::StoreInfo* SetOperation::add_store_info() {
  // @@protoc_insertion_point(field_add:SetOperation.store_info)
  return store_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
SetOperation::store_info() const {
  // @@protoc_insertion_point(field_list:SetOperation.store_info)
  return store_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
SetOperation::mutable_store_info() {
  // @@protoc_insertion_point(field_mutable_list:SetOperation.store_info)
  return &store_info_;
}

// repeated .ColumnValue primary_key = 2;
inline int SetOperation::primary_key_size() const {
  return primary_key_.size();
}
inline void SetOperation::clear_primary_key() {
  primary_key_.Clear();
}
inline const ::ColumnValue& SetOperation::primary_key(int index) const {
  // @@protoc_insertion_point(field_get:SetOperation.primary_key)
  return primary_key_.Get(index);
}
inline ::ColumnValue* SetOperation::mutable_primary_key(int index) {
  // @@protoc_insertion_point(field_mutable:SetOperation.primary_key)
  return primary_key_.Mutable(index);
}
inline ::ColumnValue* SetOperation::add_primary_key() {
  // @@protoc_insertion_point(field_add:SetOperation.primary_key)
  return primary_key_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
SetOperation::primary_key() const {
  // @@protoc_insertion_point(field_list:SetOperation.primary_key)
  return primary_key_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
SetOperation::mutable_primary_key() {
  // @@protoc_insertion_point(field_mutable_list:SetOperation.primary_key)
  return &primary_key_;
}

// repeated .ColumnValue value = 3;
inline int SetOperation::value_size() const {
  return value_.size();
}
inline void SetOperation::clear_value() {
  value_.Clear();
}
inline const ::ColumnValue& SetOperation::value(int index) const {
  // @@protoc_insertion_point(field_get:SetOperation.value)
  return value_.Get(index);
}
inline ::ColumnValue* SetOperation::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:SetOperation.value)
  return value_.Mutable(index);
}
inline ::ColumnValue* SetOperation::add_value() {
  // @@protoc_insertion_point(field_add:SetOperation.value)
  return value_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
SetOperation::value() const {
  // @@protoc_insertion_point(field_list:SetOperation.value)
  return value_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
SetOperation::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:SetOperation.value)
  return &value_;
}

// -------------------------------------------------------------------

// DeleteOperation

// repeated .StoreInfo store_info = 1;
inline int DeleteOperation::store_info_size() const {
  return store_info_.size();
}
inline void DeleteOperation::clear_store_info() {
  store_info_.Clear();
}
inline const ::StoreInfo& DeleteOperation::store_info(int index) const {
  // @@protoc_insertion_point(field_get:DeleteOperation.store_info)
  return store_info_.Get(index);
}
inline ::StoreInfo* DeleteOperation::mutable_store_info(int index) {
  // @@protoc_insertion_point(field_mutable:DeleteOperation.store_info)
  return store_info_.Mutable(index);
}
inline ::StoreInfo* DeleteOperation::add_store_info() {
  // @@protoc_insertion_point(field_add:DeleteOperation.store_info)
  return store_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
DeleteOperation::store_info() const {
  // @@protoc_insertion_point(field_list:DeleteOperation.store_info)
  return store_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
DeleteOperation::mutable_store_info() {
  // @@protoc_insertion_point(field_mutable_list:DeleteOperation.store_info)
  return &store_info_;
}

// repeated .ColumnValue primary_key = 2;
inline int DeleteOperation::primary_key_size() const {
  return primary_key_.size();
}
inline void DeleteOperation::clear_primary_key() {
  primary_key_.Clear();
}
inline const ::ColumnValue& DeleteOperation::primary_key(int index) const {
  // @@protoc_insertion_point(field_get:DeleteOperation.primary_key)
  return primary_key_.Get(index);
}
inline ::ColumnValue* DeleteOperation::mutable_primary_key(int index) {
  // @@protoc_insertion_point(field_mutable:DeleteOperation.primary_key)
  return primary_key_.Mutable(index);
}
inline ::ColumnValue* DeleteOperation::add_primary_key() {
  // @@protoc_insertion_point(field_add:DeleteOperation.primary_key)
  return primary_key_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
DeleteOperation::primary_key() const {
  // @@protoc_insertion_point(field_list:DeleteOperation.primary_key)
  return primary_key_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
DeleteOperation::mutable_primary_key() {
  // @@protoc_insertion_point(field_mutable_list:DeleteOperation.primary_key)
  return &primary_key_;
}

// -------------------------------------------------------------------

// GetOperation

// repeated .StoreInfo store_info = 1;
inline int GetOperation::store_info_size() const {
  return store_info_.size();
}
inline void GetOperation::clear_store_info() {
  store_info_.Clear();
}
inline const ::StoreInfo& GetOperation::store_info(int index) const {
  // @@protoc_insertion_point(field_get:GetOperation.store_info)
  return store_info_.Get(index);
}
inline ::StoreInfo* GetOperation::mutable_store_info(int index) {
  // @@protoc_insertion_point(field_mutable:GetOperation.store_info)
  return store_info_.Mutable(index);
}
inline ::StoreInfo* GetOperation::add_store_info() {
  // @@protoc_insertion_point(field_add:GetOperation.store_info)
  return store_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::StoreInfo >&
GetOperation::store_info() const {
  // @@protoc_insertion_point(field_list:GetOperation.store_info)
  return store_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::StoreInfo >*
GetOperation::mutable_store_info() {
  // @@protoc_insertion_point(field_mutable_list:GetOperation.store_info)
  return &store_info_;
}

// repeated .ColumnValue primary_key = 2;
inline int GetOperation::primary_key_size() const {
  return primary_key_.size();
}
inline void GetOperation::clear_primary_key() {
  primary_key_.Clear();
}
inline const ::ColumnValue& GetOperation::primary_key(int index) const {
  // @@protoc_insertion_point(field_get:GetOperation.primary_key)
  return primary_key_.Get(index);
}
inline ::ColumnValue* GetOperation::mutable_primary_key(int index) {
  // @@protoc_insertion_point(field_mutable:GetOperation.primary_key)
  return primary_key_.Mutable(index);
}
inline ::ColumnValue* GetOperation::add_primary_key() {
  // @@protoc_insertion_point(field_add:GetOperation.primary_key)
  return primary_key_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
GetOperation::primary_key() const {
  // @@protoc_insertion_point(field_list:GetOperation.primary_key)
  return primary_key_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
GetOperation::mutable_primary_key() {
  // @@protoc_insertion_point(field_mutable_list:GetOperation.primary_key)
  return &primary_key_;
}

// repeated .ColumnValue value = 3;
inline int GetOperation::value_size() const {
  return value_.size();
}
inline void GetOperation::clear_value() {
  value_.Clear();
}
inline const ::ColumnValue& GetOperation::value(int index) const {
  // @@protoc_insertion_point(field_get:GetOperation.value)
  return value_.Get(index);
}
inline ::ColumnValue* GetOperation::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:GetOperation.value)
  return value_.Mutable(index);
}
inline ::ColumnValue* GetOperation::add_value() {
  // @@protoc_insertion_point(field_add:GetOperation.value)
  return value_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ColumnValue >&
GetOperation::value() const {
  // @@protoc_insertion_point(field_list:GetOperation.value)
  return value_;
}
inline ::google::protobuf::RepeatedPtrField< ::ColumnValue >*
GetOperation::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:GetOperation.value)
  return &value_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ManipulationOperations_2eproto__INCLUDED
